### ISSUE TITLE
Center timer and buttons both vertically and horizontally

### ISSUE THREAD

**Issue by VickyKoblinski** [VickyKoblinski/collab-timer#3]
Right now the timer is on the top right and it looks pretty ugly. We would like that centered to the middle of the screen.

If a css file does not exist, please create one.

@kluu1

**Comment by tmwlsh** [comment]
Hi @VickyKoblinski, ive done a pull request for this. could you review and accept it please?

**Comment by VickyKoblinski** [comment]
Thanks @tmwlsh! I appreciate the enthusiasm! 👍 Next time though, could you look for a ticket that is not assigned and make a comment before beginning your work? That way the effort isn't getting doubled.

**Comment by VickyKoblinski** [comment]
Completed by https://github.com/VickyKoblinski/collab-timer/pull/11
